# Numpy

## -->Numpy is a Fundamental package for scientific computing in python. It is a Python library that provides a multi dimensional Array object and various derived objects such as Masked Array or Matrices and an assortment of routine for fast operation on Array including Mathematical, logical , shape manipulation, sorting, selecting, I/O, discrete fourier transform, basic linear algebra, statiscal operations , Random simulation etc.

## -->At the core of the Numpy Package is the n-dimensional array object

## Why Numpy?
## -->We needed Speed and Less memory to work with a huge amount of data
numpy --> c langauge --> wrapped --> Python language
## -->Numpy --> syntax --> Easy for beginner --> Performing scientific calculations --> Creating multi dimensional array --> Speed is faster for appying operation --> Less memory

## Libraries like Scikit Learn, Tensorflow and PyTorch require input data in Numpy Array or Tensor

## Numpy Array Vs Python Sequences 

## Numpy Array  
### -->Numpy Arrays have a fixed size at creation unlike Python lists which grow dynamically. Changing the size of an N- Dimentional Array will create a new Array and delete the original.
### -->The elements in a Numpy Array arey required to be of the same data type and thus will be of the same size in memory.
### -->Numpy Arrays facilitate advanceed Mathematical and other types of operation on large number of Data. Typically, such operations are executed more efficiently with less code than is possible using Python's built in sequences.
### -->

In [ ]:
pip install 


[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [14]:
# 1-D Array or vector array , single [] will be used
numpy_array = np.array([1,2,3,4,5])             

In [5]:
print(numpy_array)

[1 2 3 4 5]


In [16]:
type(numpy_array)           #numpy.ndarray -- ndarray -- n dimentional array

numpy.ndarray

In [15]:
# 2-D Array or Matrice ,  double [[]] will be use
two_dim_array = np.array([[1,2,3,4,5],[6,7,8,9,0],[5,4,3,2,8]])         

In [9]:
print(two_dim_array)

[[1 2 3 4 5]
 [6 7 8 9 0]
 [5 4 3 2 8]]


In [17]:
# 3-D Array or Tensor , Tripple [[[]]] will be used 
three_dim_array = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,0],[5,6]]])

In [18]:
print(three_dim_array)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[9 0]
  [5 6]]]


## np.array() -->Creating the Multi-dimensional Array


### dtype parameter --> which can help us out with deciding about the size of the data we are going to store inside our array

In [20]:
np.array([1,2,3,4,5,6], dtype = np.int32)          # each elemnt is going to be 32-bit

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [21]:
np.array([5,4,7,9,3], dtype = np.int64)             # each elemnt is going to be 64-bit

array([5, 4, 7, 9, 3])

In [22]:
# np.float32 or np.float64

In [25]:
np.array([5,4,7,9,3], dtype = float) 

array([5., 4., 7., 9., 3.])

In [27]:
np.array([5,4,7,9,3], dtype = int)          # by default int dtype

array([5, 4, 7, 9, 3])

In [31]:
np.array([1,2,4,1,0] , dtype = bool)

array([ True,  True,  True,  True, False])

In [36]:
# data filling 1 to 15 into empty list [] using List , use of range() function
empty_list = []
for i in range(16):
    empty_list.append(i)
print(empty_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [35]:
# data filling 1 to 15 into empty list using Numpy, use of arange() function
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

## arange() --> It help us out with providing the values over a certain range

In [37]:
np.arange(1,17)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [40]:
np.arange(5,21)    # arange(first_Value, last_value-1)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [41]:
np.arange(1,21,2)           # arange(first_value, last_value-1, difference_between_value)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [50]:
# use of arange() and reshape
# arange() -->store in the array
# reshape(row,column) --> shape the arrange value into n-dimension array

arange_data = np.arange(1,17)
print(arange_data)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [45]:
arange_data.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [46]:
arange_data2 = np.arange(1,10)
arange_data2.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## np.reshape() -->It helps us out with changing the shape of the array as per our needs

In [47]:
arange_data.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [49]:
# arange_data.reshape(2,6)  --- throw error
# arange_data.reshape(2,10)  -- throw error

In [53]:
np.arange(1,17,2).reshape(2,4)

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15]])

In [54]:
np.arange(1,17,2).reshape(4,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

In [59]:
np.ones((4,4))         # pass row and column inside tuple, by default float, convert using dtype if you want

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [60]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

## np.ones(row,column) -->Initialize the weight of the neurons in the neural network architechture

In [57]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [58]:
np.zeros((4,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## random() -->It helps us out with generating any random values from 0 to 1 inside our matrix

In [71]:
np.random.random((3,4))

array([[0.55311805, 0.62159693, 0.26490159, 0.55797467],
       [0.54880323, 0.72676255, 0.47554836, 0.81170264],
       [0.06714129, 0.1917023 , 0.61752356, 0.86820329]])

## indentity() -->It helps us out with creating the matrix as an indentity matrix (Square matrix --> row=column) 

In [82]:
#np.identity(3)          # same as np.identity(3,3) or np.eye(3)
#np.eye(4,4)
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

## linspace() -->It makes sure that every value with the given range is going to have similar distance from each other 

In [86]:
#linspace(starting_value ,end_value, number_of_values)
np.linspace(-10,10,5)

array([-10.,  -5.,   0.,   5.,  10.])

# Atrribute

## 1. ndim attribute -->ndim stands for ndimension
## 2. shape attribute -->It provides us with the idea about the rows, columns in our dataset or in array
## 3. size attribute -->Total number of element inside our dataset or Array
## 4. itemsize -->Provides with the idea about the size of a unique element inside our Array in bytes.
## 5. dtype -->It provides witht the idea about the type of every item inside our Array.

In [ ]:
# ndim 

In [94]:
# 1-D Array
arr = np.array([1,2,3,4])

In [90]:
print(arr)

[1 2 3 4]


In [93]:
arr.ndim            # 1 dimension

1

In [97]:
# 2-Day Array
twoDArray = np.array([[3,4],[6,8],[4,1]])

In [98]:
print(twoDArray)

[[3 4]
 [6 8]
 [4 1]]


In [100]:
twoDArray.ndim          # 2-D

2

In [102]:
# 3-dimension Array
threeDArray = np.array([[[1,2],[3,4]],[[5,6],[7,8]],])

In [103]:
print(threeDArray)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [105]:
threeDArray.ndim            # 3-D

3

In [106]:
# shape

In [107]:
two_dim_arr = np.array([[1,2],[5,6],[8,9]])

In [108]:
print(two_dim_arr)

[[1 2]
 [5 6]
 [8 9]]


In [110]:
two_dim_arr.shape       # 3 rows, 2 columns

(3, 2)

In [124]:
three_dim_arr = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,0],[11,12]],[[13,14],[15,16],[17,18]]])

In [125]:
print(three_dim_arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9  0]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


In [126]:
three_dim_arr.shape

(3, 3, 2)

In [127]:
# size

In [128]:
a = np.arange(5,57)

In [129]:
a.size

52

In [130]:
# itemsize

In [131]:
np.array([[1,2],[3,4],[5,6]]).itemsize

8

In [132]:
np.array([[1,2],[3,4],[5,6]], dtype = np.int32).itemsize

4

In [133]:
# dtype

In [138]:
np.array([[6,7],[8,9]]).dtype           # by default 64 bit

dtype('int64')

In [137]:
np.array([[6,7],[8,9]], dtype = np.int32).dtype

dtype('int32')

# astype() 
## -->astype() is helping us out with figuring out the data type of the column in dataset in Pandas and it will be used in Numpy as well for getting the data type changed of our overall Array.

In [7]:
import numpy as np
array = np.arange(1,10)
# or array = np.arange(1,10).reshape(3,3)

In [3]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
array.reshape(3,3)      # data type is in int

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
type(array)     #type of array

numpy.ndarray

In [15]:
array.dtype             #data type of array variable here

dtype('float64')

In [17]:
array=array.astype('float64')       # changing the data type of array from int to float using astype()

In [18]:
array.dtype         # now the data type has been changed to float

dtype('float64')

# Mathematical operation in Numpy

## Scalar Operation
## -->A Scalar value operation will be done with the Array or a Numeric value eg(1,4)

In [35]:
arr = np.random.random((3,3))*100
print(arr)

[[43.13597051 37.68406191 72.4099755 ]
 [24.74202115 66.52943738 67.84901413]
 [46.05549031 46.15067283 87.44318285]]


In [36]:
arr = np.round(arr)
print(arr)

[[43. 38. 72.]
 [25. 67. 68.]
 [46. 46. 87.]]


In [37]:
arr = arr.astype('int32')

In [38]:
print(arr)

[[43 38 72]
 [25 67 68]
 [46 46 87]]


In [51]:
# Scalar operations with our Matrix or Array

In [47]:
# addition
arr+2
#print(arr+2)


array([[45, 40, 74],
       [27, 69, 70],
       [48, 48, 89]], dtype=int32)

In [48]:
# substraction
arr-5

array([[38, 33, 67],
       [20, 62, 63],
       [41, 41, 82]], dtype=int32)

In [49]:
#multiplication
arr*2

array([[ 86,  76, 144],
       [ 50, 134, 136],
       [ 92,  92, 174]], dtype=int32)

In [50]:
#division
arr/2

array([[21.5, 19. , 36. ],
       [12.5, 33.5, 34. ],
       [23. , 23. , 43.5]])

In [52]:
# We can apply Scalar operation with the Array in terms of Arithmetic operations

In [53]:
a=5
b=6
a>b

False

In [54]:
arr

array([[43, 38, 72],
       [25, 67, 68],
       [46, 46, 87]], dtype=int32)

In [55]:
arr>50

array([[False, False,  True],
       [False,  True,  True],
       [False, False,  True]])

## Vector Operations
## -->Operations will be in between the given number of Matrices

In [59]:
arr1 = np.arange(1,17).reshape(4,4)

In [60]:
arr2 = np.arange(17,33).reshape(4,4)

In [61]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [62]:
arr2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [69]:
arr1 + arr2           # addition

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [70]:
arr2 - arr1               # substraction

array([[16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16]])

In [71]:
arr1 * arr2         # multiplication

array([[ 17,  36,  57,  80],
       [105, 132, 161, 192],
       [225, 260, 297, 336],
       [377, 420, 465, 512]])

## Important Function in Numpy for Machine Learning and Data Science

## 1. max() -->It is going to be used to calculate the maximum value inside a Matrix or an Array
## Syntax for max() --> np.max(array_name)

In [72]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [75]:
# MAXIMUM VALUE INSIDE THE ARRAY arr1
arr1_max = np.max(arr1)

In [74]:
print(arr1_max)

16


In [78]:
array_data = np.round(np.random.random((3,3)) * 100).astype('int32')

In [79]:
print(array_data)

[[ 3 86 97]
 [38 50 15]
 [65 68 44]]


## axis 
## -->It provides us with idea about the any operation value inside a specific row or column or we can get a specific value row wise aur column wise
## --> axis = 0 ---> Column wise operation
## --> axis = 1 ---> Row wise operation

In [82]:
arrr = np.round(np.random.random((5,5)) * 100).astype('int32')

In [83]:
arrr

array([[37, 96,  1, 70,  9],
       [81, 38, 99, 37,  1],
       [32, 73, 12, 29, 75],
       [93, 40, 89, 74, 75],
       [24, 25, 80, 41, 75]], dtype=int32)

In [85]:
np.max(arrr, axis =0)       # checking the maximum value in Array 'arrr' column wise so i am using axis = 0

array([93, 96, 99, 74, 75], dtype=int32)

In [86]:
np.max(arrr, axis = 1)          # checking the maximum value in Array 'arrr' row wise so i am using axis = 1

array([96, 99, 75, 93, 80], dtype=int32)

## 2. min() 
## -->It will be used for calculating the minimum value from the Matrix or An Array
## Syntax --> np.min(array_name)

In [87]:
arrr

array([[37, 96,  1, 70,  9],
       [81, 38, 99, 37,  1],
       [32, 73, 12, 29, 75],
       [93, 40, 89, 74, 75],
       [24, 25, 80, 41, 75]], dtype=int32)

In [90]:
print(np.min(arrr))         # minimum value from 'arrr' array

1


In [92]:
np.min(arrr, axis = 0)          # minimum value column wise inside the Array 'arrr'

array([24, 25,  1, 29,  1], dtype=int32)

In [93]:
np.min(arrr, axis =1)           # minimum value row wise inside the Array 'arrr'

array([ 1,  1, 12, 40, 24], dtype=int32)

In [94]:
ar = np.arange(1, 10)

In [95]:
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
np.min(ar)

np.int64(1)

In [97]:
np.max(ar)

np.int64(9)

## 3. sum()
## -->Calculates the sum of all of the values of a given matrix
## -->Syntax ---> np.sum(array_name)

In [98]:
arr_sum = np.round(np.random.random((5,5)) * 100).astype('int32')

In [99]:
print(arr_sum)

[[88  8 68 41  0]
 [89  8 16 68 43]
 [45 83 70  3 90]
 [75 88 54 78 56]
 [77  3 85 80 72]]


In [100]:
np.sum(arr_sum)             # sum of all the values inside Array 'arr_sum'

np.int64(1388)

In [101]:
np.sum(arr_sum, axis = 0)             # sum of all the values column wise inside arr_sum

array([374, 190, 293, 270, 261])

In [102]:
np.sum(arr_sum, axis = 1)              # sum of all the values row wise inside arr_sum

array([205, 224, 291, 351, 317])

## 4. prod()
## -->Calculates the product of all values inside the Matrix or Array
## -->Syntax ---> np.prod(array_name)

In [103]:
arr_prod = np.arange(1,10).reshape((3,3))

In [104]:
print(arr_prod)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [106]:
print(np.prod(arr_prod))

362880


In [107]:
ar_prod = np.arange(1,10)
print(ar_prod)

[1 2 3 4 5 6 7 8 9]


In [109]:
print(np.prod(ar_prod))

362880


In [111]:
np.prod(arr_prod,axis=0)        # column wise multiplication

array([ 28,  80, 162])

In [112]:
np.prod(arr_prod,axis=1)         # row wise multiplication

array([  6, 120, 504])

# Statistical Function in Numpy

## 1. mean() 
## -->It provides mean of all values inside the Matrix or Array.
## -->Syntax ---> np.mean(array_name)

## 2. std()
## -->It provides Standard Deviation of all values of the Matrix or Array
## syntax -->np.std(array_name)

## 3. median()
## -->To calculate median of all values in the Array or Matrix
## --syntax --->np.median(array_name)

## 4. var()
## -->Calculates the Variance of all values inside our Matrix or Array
## -->syntax --->np.var(array_name)

In [121]:
# mean()
arr_mean = np.round(np.random.random((4,4)) * 100).astype('int32')

In [114]:
print(arr_mean)

[[77 59 10 79]
 [81  2 76 11]
 [16 60 95 36]
 [88 32 39 73]]


In [117]:
print(np.mean(arr_mean))        # mean of all the values 

52.125


In [119]:
print(np.mean(arr_mean, axis = 0))          # mean of values column wise

[65.5  38.25 55.   49.75]


In [120]:
print(np.mean(arr_mean , axis = 1))         # mean of values row wise

[56.25 42.5  51.75 58.  ]


In [129]:
# Standard Deviation std()
arr_std = np.round(np.random.random((4,4)) * 100).astype('int32')

In [123]:
print(arr_std)

[[57 99 42 21]
 [18 67 90 93]
 [47 19  4 62]
 [98 97 54 98]]


In [125]:
print(np.std(arr_std))

32.07194061792956


In [126]:
print(np.std(arr_std,axis=0))

[28.6618213  32.32259272 30.70423424 30.69609096]


In [127]:
print(np.std(arr_std,axis=1))

[28.56899543 30.02498959 22.77059507 18.91262806]


In [128]:
# median()

In [130]:
arr_median = np.round(np.random.random((3,3)) * 100).astype('int32')

In [131]:
print(np.median(arr_median))

55.0


In [132]:
print(np.median(arr_median, axis = 0))

[47. 70. 55.]


In [133]:
print(np.median(arr_median, axis = 1))

[16. 76. 47.]


In [ ]:
# var()

In [135]:
arr_variance = np.round(np.random.random((4,4)) * 100).astype('int32')

In [139]:
print(np.var(arr_variance))         # variance of all values

818.0


In [138]:
print(np.var(arr_variance, axis = 0))           # columnwise variance

[ 318.1875  695.5    1257.      750.6875]


In [140]:
print(np.var(arr_variance, axis = 1))           # row wise variance

[1074.      126.5     658.6875  939.6875]


## Trigonometry Functions

## sin()
## cos()
## tan()

In [4]:
import numpy as np
print(np.sin(90))

0.8939966636005579


In [5]:
print(np.cos(45))

0.5253219888177297


In [7]:
print(np.tan(0))

0.0


## DOT Product of Matrix
## Syntax --> np.dot(matrix1, matrix2)

In [8]:
matrix1 = np.round(np.random.random((3,4)) * 100).astype('int32')
matrix2 = np.round(np.random.random((4,3)) * 100).astype('int32')

In [9]:
matrix1

array([[59, 81, 28,  6],
       [74, 25, 92, 64],
       [13, 67, 64,  9]], dtype=int32)

In [10]:
matrix2

array([[81, 68, 69],
       [30, 84, 87],
       [50, 28, 34],
       [68, 23,  7]], dtype=int32)

In [11]:
np.dot(matrix1,matrix2)

array([[ 9017, 11738, 12112],
       [15696, 11180, 10857],
       [ 6875,  8511,  8965]], dtype=int32)

## log()
## -->To calculate the log of the Matrix
## -->syntax --->np.log(array_name)

In [12]:
matrix1

array([[59, 81, 28,  6],
       [74, 25, 92, 64],
       [13, 67, 64,  9]], dtype=int32)

In [13]:
np.log(matrix1)

array([[4.07753744, 4.39444915, 3.33220451, 1.79175947],
       [4.30406509, 3.21887582, 4.52178858, 4.15888308],
       [2.56494936, 4.20469262, 4.15888308, 2.19722458]])

## exp()
## -->Exponential of all values inside a Matrix
## -->Syntax ---> np.exp(array_name)

In [14]:
matrix1

array([[59, 81, 28,  6],
       [74, 25, 92, 64],
       [13, 67, 64,  9]], dtype=int32)

In [15]:
np.exp(matrix1)

array([[4.20121040e+25, 1.50609731e+35, 1.44625706e+12, 4.03428793e+02],
       [1.37338298e+32, 7.20048993e+10, 9.01762841e+39, 6.23514908e+27],
       [4.42413392e+05, 1.25236317e+29, 6.23514908e+27, 8.10308393e+03]])

## round()
## -->It helps with rounding off the float values to its nearest possible integer value
## -->Syntax ---> np.round(matrix)

In [16]:
arr1 = np.random.random((3,4))

In [17]:
arr1

array([[0.35847138, 0.50412488, 0.26878119, 0.6852197 ],
       [0.28091263, 0.95471673, 0.89890217, 0.60097316],
       [0.5255336 , 0.71122896, 0.96797243, 0.14186423]])

In [19]:
arr1 = arr1 * 10
print(arr1)

[[35.84713806 50.41248763 26.87811912 68.52197028]
 [28.09126279 95.47167252 89.89021746 60.09731602]
 [52.5533598  71.12289561 96.79724262 14.18642273]]


In [20]:
np.round(arr1)

array([[36., 50., 27., 69.],
       [28., 95., 90., 60.],
       [53., 71., 97., 14.]])

In [21]:
'''
round() -- 1.3>1 , 1.7>2
ceil() -- 1.3>2 , 1.6>2         # next possible value
floor() -- 3.6>2 , 3.4>3        #previoud possible value
'''

'\nround() -- 1.3>1 , 1.7>2\nceil() -- 1.3>2 , 1.6>2         # next possible value\nfloor() -- 3.6>2 , 3.4>3        #previoud possible value\n'

In [22]:
arr1

array([[35.84713806, 50.41248763, 26.87811912, 68.52197028],
       [28.09126279, 95.47167252, 89.89021746, 60.09731602],
       [52.5533598 , 71.12289561, 96.79724262, 14.18642273]])

In [25]:
np.ceil(arr1)           # next possible value

array([[36., 51., 27., 69.],
       [29., 96., 90., 61.],
       [53., 72., 97., 15.]])

In [26]:
np.floor(arr1)           # previous possible value

array([[35., 50., 26., 68.],
       [28., 95., 89., 60.],
       [52., 71., 96., 14.]])

## transpose()
## --> To calculate the transpose of the given Matrix
## --> syntax ---> np.transpose(array_name) or arrany_name.T
## -->Transpose -->(i,j) --> (j,i) --> (3,4) --> (4,3)

In [27]:
arr_transpose = np.arange(1,13).reshape(3,4)
arr_transpose

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
arr_transpose.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [29]:
#or, 
np.transpose(arr_transpose)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

## ravel()
## -->convert N-D array into 1-D array
## -->syntax --> np.ravel(array_name)

In [30]:
arr_ravel = np.arange(1,13).reshape(3,4)
arr_ravel

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
arr_ravel.ndim          # checking the dimension of this array which is 2-D array

2

In [35]:
arr_ravel1 = np.ravel(arr_ravel)         # converted from 2-D array to 1-D array

In [36]:
arr_ravel1.ndim

1

## Indexing and Slicing in Numpy

In [37]:
# Indexing --> lists[,size-1] --> To have the access over the values

In [40]:
arr_index = np.arange(1,10)         # 1-D array for accessing
arr_index

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr_index[5]            # access the value on index 5

np.int64(6)

In [46]:
#now same for the 2-D array
arr_index1 = np.round(np.random.random((5,5)) * 100).astype('int32')

In [47]:
print(arr_index1)

[[14 90 36 88 11]
 [78 48 66  3 50]
 [52 50 55 49 53]
 [29 47 52 57 61]
 [89 48 37  5 55]]


In [48]:
arr_index1.ndim

2

In [51]:
arr_index1[4,4]     # access over 2-d array, array_name[row,column]

np.int32(55)

In [52]:
arr_index1[0,0]

np.int32(14)

In [1]:
## Indexing in 2-D array --> array_name[row,column]
## Indexing in 3-D array --> array_name[z-axis, x-axis, y-axis]

In [57]:
# 3-D array
arr_3D = np.arange(1,9).reshape(2,2,2)  # z,x=row, y=column
arr_3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [60]:
arr_3D[0,0,0]


np.int64(1)

In [61]:
print(arr_3D[0,0,1])

2


In [62]:
print(arr_3D[1,0,1])

6


## Slicing --> similar to approach just like the list[:]
## 2-D Array --> [row1:row2 ,col1:col2 ]

In [3]:
import numpy as np
arr_slicing = np.round(np.random.random((5,5)) * 100).astype('int32')
arr_slicing

array([[34, 52, 48, 72, 93],
       [24, 39, 36,  1, 28],
       [23, 27, 69, 42, 91],
       [97, 14, 51, 17, 44],
       [76, 61, 20,  2, 47]], dtype=int32)

In [4]:
arr_slicing[:,2]        # 3rd column only

array([48, 36, 69, 51, 20], dtype=int32)

In [5]:
arr_slicing[0,:]         # 1st row only

array([34, 52, 48, 72, 93], dtype=int32)

In [7]:
# i want  below data
# 69,42         -->3rd row and 3rd&4th column
# 51,17         -->4th roe and 3rd&4th column

arr_slicing[2:4,2:4]        # 2:4 --> 3rd and 4th row included(5 index-1) , 2:4 --> 3rd & 4th column will be inlcuded(5 index-1) 

array([[69, 42],
       [51, 17]], dtype=int32)

In [8]:
# I want below data
# 27, 69, 42
# 14, 51, 17
# 61, 20, 2

arr_slicing[2:,1:4]

array([[27, 69, 42],
       [14, 51, 17],
       [61, 20,  2]], dtype=int32)

In [10]:
arr_1d = np.arange(1,10)
arr_1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
for i in arr_1d:        # iteration in 1D array
    print(i)

1
2
3
4
5
6
7
8
9


In [13]:
arr_2d = np.arange(1,17).reshape(4,4)
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [15]:
for i in arr_2d:        # iteration in 2D array
    print(i)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]


In [16]:
arr_3d = np.arange(1,28).reshape(3,3,3)
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [17]:
for i in arr_3d:
    print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[19 20 21]
 [22 23 24]
 [25 26 27]]


In [18]:
# nditer() --> Help with iterating over every value in a N-D Array
# syntax --> np.nditer()

In [19]:
for i in np.nditer(arr_3d):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27


In [20]:
# 1D Array --> Value by value on iteration
# 2D Array --> row by row on iteration
# 3D Array --> 2D array by 2D array

## Stacking and Spliting in Array
## --> Size of the Array must be same
## Stacking
## 1. Horizontal Stacking --> Row by Row joining --> hstack()
## 2. Vertical Stackign --> Column by Column joining --> vstack()
## Spliting
## 1. Horizontal Split --> hsplit(array, number of parts you want your array splited)
## 2. Vertical Split --> vsplit(array, number of parts)

In [21]:
arr_stack1 = np.arange(1,13).reshape(3,4)
arr_stack1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
arr_stack2 = np.arange(13,25).reshape(3,4)
arr_stack2

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [36]:
# Horizontal stacking

horizontal_array = np.hstack((arr_stack1,arr_stack2))       # we have to pass the value as a tuple so we used two parenthesis here otherwise it will throw error
horizontal_array

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

In [28]:
horizontal_array = np.hstack((arr_stack1,arr_stack1))
horizontal_array

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12]])

In [30]:
horizontal_array = np.hstack((arr_stack2,arr_stack2))
horizontal_array

array([[13, 14, 15, 16, 13, 14, 15, 16],
       [17, 18, 19, 20, 17, 18, 19, 20],
       [21, 22, 23, 24, 21, 22, 23, 24]])

In [32]:
horizontal_array = np.hstack((arr_stack1,arr_stack2,arr_stack1 ,arr_stack2))
horizontal_array

array([[ 1,  2,  3,  4, 13, 14, 15, 16,  1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20,  5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24,  9, 10, 11, 12, 21, 22, 23, 24]])

In [38]:
# Vertical Stacking

vertical_array = np.vstack((arr_stack1,arr_stack2))
vertical_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [40]:
horizontal_split = np.hsplit(vertical_array , 2)
horizontal_split

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]

In [44]:
horizontal_split = np.hsplit(vertical_array,4)
horizontal_split

[array([[ 1],
        [ 5],
        [ 9],
        [13],
        [17],
        [21]]),
 array([[ 2],
        [ 6],
        [10],
        [14],
        [18],
        [22]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19],
        [23]]),
 array([[ 4],
        [ 8],
        [12],
        [16],
        [20],
        [24]])]

In [45]:
vertical_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [49]:
vertical_split = np.vsplit(vertical_array, 2)
vertical_split

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [51]:
vertical_split = np.vsplit(vertical_array,3)         # while spliting into 4 part it will throw error because it wont be divisible int 4 equal parts
vertical_split

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]])]